# This is a monorepo. You must configure Railway to use a Root Directory.
# For backend: Set Root Directory to /backend
# For frontend: Set Root Directory to /frontend
# See DEPLOY_RAILWAY_QUICKSTART.md for instructions

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["echo 'ERROR: Please set Root Directory to /backend or /frontend in Railway Settings'", "exit 1"]
